In [1]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.7.1
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License:
Location: C:\Users\Asus\anaconda3\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: imbalanced-learn

In [2]:
import pandas as pd
import numpy as np

In [3]:
odi_ball= pd.read_csv('ODI_ball_by_ball_data.csv')
odi_match= pd.read_csv('ODI_match_data.csv')

C:\Users\Asus\AppData\Local\Temp\ipykernel_23252\4053476724.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  odi_ball= pd.read_csv('ODI_ball_by_ball_data.csv')

In [4]:
odi_ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1453620 entries, 0 to 1453619
Data columns (total 24 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id                 1453620 non-null  int64
 1   season             1453620 non-null  object
 2   venue              1453620 non-null  object
 3   batting_team       1453620 non-null  object
 4   bowling_team       1453620 non-null  object
 5   innings            1453620 non-null  int64
 6   over               1453620 non-null  int64
 7   ball               1453620 non-null  int64
 8   is_super_over      1453620 non-null  int64
 9   batter             1453620 non-null  object
 10  non_striker        1453620 non-null  object
 11  bowler             1453620 non-null  object
 12  runs_off_bat       1453620 non-null  int64
 13  runs_from_extras   1453620 non-null  int64
 14  total_runs         1453620 non-null  int64
 15  is_wkt_delivery    1453620 non-null  int64
 16  player_out         39486 non-null    object
 17  wkt_type           39486 non-null    object
 18  fielders_involved  25480 non-null    object
 19  byes               1453620 non-null  int64
 20  legbyes            1453620 non-null  int64
 21  wides              1453620 non-null  int64
 22  noballs            1453620 non-null  int64
 23  penalty            1453620 non-null  int64
dtypes: int64(14), object(10)
memory usage: 266.2+ MB

In [5]:
odi_match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2731 entries, 0 to 2730
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2731 non-null   int64
 1   date               2731 non-null   object
 2   season             2731 non-null   object
 3   gender             2731 non-null   object
 4   event_name         2715 non-null   object
 5   match_type         2731 non-null   object
 6   match_type_number  2731 non-null   int64
 7   match_number       2632 non-null   object
 8   city               2396 non-null   object
 9   venue              2731 non-null   object
 10  team1              2731 non-null   object
 11  team2              2731 non-null   object
 12  referee            2694 non-null   object
 13  reserve_umpire     2301 non-null   object
 14  tv_umpire          2249 non-null   object
 15  umpire1            2730 non-null   object
 16  umpire2            2730 non-null   object
 17  team1players       2731 non-null   object
 18  team2players       2731 non-null   object
 19  toss_winner        2731 non-null   object
 20  toss_decision      2731 non-null   object
 21  winner             2600 non-null   object
 22  result             131 non-null    object
 23  eliminator         5 non-null      object
 24  wonBy              2600 non-null   object
 25  margin             2600 non-null   float64
 26  method             223 non-null    object
 27  player_of_match    2527 non-null   object
dtypes: float64(1), int64(2), object(25)
memory usage: 597.5+ KB

In [6]:
odi_ball.head()

,id,season,venue,batting_team,bowling_team,innings,over,ball,is_super_over,batter,...,total_runs,is_wkt_delivery,player_out,wkt_type,fielders_involved,byes,legbyes,wides,noballs,penalty
0,1000887,2016/17,"Brisbane Cricket Ground, Woolloongabba",Australia,Pakistan,1,0,1,0,DA Warner,...,0,0,NaN,NaN,NaN,0,0,0,0,0
1,1000887,2016/17,"Brisbane Cricket Ground, Woolloongabba",Australia,Pakistan,1,0,2,0,DA Warner,...,0,0,NaN,NaN,NaN,0,0,0,0,0
2,1000887,2016/17,"Brisbane Cricket Ground, Woolloongabba",Australia,Pakistan,1,0,3,0,DA Warner,...,0,0,NaN,NaN,NaN,0,0,0,0,0
3,1000887,2016/17,"Brisbane Cricket Ground, Woolloongabba",Australia,Pakistan,1,0,4,0,DA Warner,...,0,0,NaN,NaN,NaN,0,0,0,0,0
4,1000887,2016/17,"Brisbane Cricket Ground, Woolloongabba",Australia,Pakistan,1,0,5,0,DA Warner,...,1,0,NaN,NaN,NaN,0,0,1,0,0

In [7]:
odi_ball.shape

(1453620, 24)

In [8]:
odi_match.shape

(2731, 28)

In [9]:
odi_match.head()

,id,date,season,gender,event_name,match_type,match_type_number,match_number,city,venue,...,team2players,toss_winner,toss_decision,winner,result,eliminator,wonBy,margin,method,player_of_match
0,64814,29-12-2002,2002/03,male,India tour of New Zealand,ODI,1927,2,Napier,"McLean Park, Napier",...,"['SC Ganguly', 'V Sehwag', 'VVS Laxman', 'R Dr...",India,field,New Zealand,NaN,NaN,runs,35.0,NaN,['V Sehwag']
1,64815,01-01-2003,2002/03,male,India tour of New Zealand,ODI,1928,3,Christchurch,"Jade Stadium, Christchurch",...,"['SP Fleming', 'NJ Astle', 'MS Sinclair', 'CD ...",India,bat,New Zealand,NaN,NaN,wickets,5.0,NaN,['DR Tuffey']
2,64816,04-01-2003,2002/03,male,India tour of New Zealand,ODI,1929,4,Queenstown,"Davies Park, Queenstown",...,"['SP Fleming', 'NJ Astle', 'MS Sinclair', 'CD ...",New Zealand,field,New Zealand,NaN,NaN,wickets,7.0,NaN,['AR Adams']
3,64817,08-01-2003,2002/03,male,India tour of New Zealand,ODI,1930,5,Wellington,"Westpac Stadium, Wellington",...,"['SC Ganguly', 'V Sehwag', 'D Mongia', 'SR Ten...",New Zealand,bat,India,NaN,NaN,wickets,2.0,NaN,['Z Khan']
4,65634,09-01-2003,2002/03,male,VB Series,ODI,1931,6,Sydney,Sydney Cricket Ground,...,"['AC Gilchrist', 'ML Hayden', 'RT Ponting', 'D...",Australia,field,Sri Lanka,NaN,NaN,runs,79.0,NaN,['ST Jayasuriya']

In [10]:
odi_match['gender'].unique()

array(['male', 'female'], dtype=object)

In [11]:
target_score_df= odi_ball.groupby(['id', 'innings'])['total_runs'].sum().reset_index()

In [12]:
target_score_df= target_score_df[target_score_df['innings']== 1]

In [13]:
target_score_df['total_runs']= target_score_df['total_runs'] + 1

In [14]:
target_score_df

           id  innings  total_runs
0       64814        1         255
2       64815        1         109
4       64816        1         123
6       64817        1         169
8       64819        1         123
...       ...      ...         ...
5395  1382166        1         153
5397  1382167        1         229
5399  1382168        1         226
5401  1384542        1         205
5403  1384544        1         188

[2731 rows x 3 columns]

In [15]:
match_df= odi_match.merge(target_score_df[['id', 'total_runs']], left_on= 'id', right_on= 'id')

In [16]:
match_df.head()

,id,date,season,gender,event_name,match_type,match_type_number,match_number,city,venue,...,toss_winner,toss_decision,winner,result,eliminator,wonBy,margin,method,player_of_match,total_runs
0,64814,29-12-2002,2002/03,male,India tour of New Zealand,ODI,1927,2,Napier,"McLean Park, Napier",...,India,field,New Zealand,NaN,NaN,runs,35.0,NaN,['V Sehwag'],255
1,64815,01-01-2003,2002/03,male,India tour of New Zealand,ODI,1928,3,Christchurch,"Jade Stadium, Christchurch",...,India,bat,New Zealand,NaN,NaN,wickets,5.0,NaN,['DR Tuffey'],109
2,64816,04-01-2003,2002/03,male,India tour of New Zealand,ODI,1929,4,Queenstown,"Davies Park, Queenstown",...,New Zealand,field,New Zealand,NaN,NaN,wickets,7.0,NaN,['AR Adams'],123
3,64817,08-01-2003,2002/03,male,India tour of New Zealand,ODI,1930,5,Wellington,"Westpac Stadium, Wellington",...,New Zealand,bat,India,NaN,NaN,wickets,2.0,NaN,['Z Khan'],169
4,65634,09-01-2003,2002/03,male,VB Series,ODI,1931,6,Sydney,Sydney Cricket Ground,...,Australia,field,Sri Lanka,NaN,NaN,runs,79.0,NaN,['ST Jayasuriya'],344

In [17]:
match_df['team1'].unique()

array(['New Zealand', 'India', 'Sri Lanka', 'Australia', 'England',
       'West Indies', 'Zimbabwe', 'Canada', 'Kenya', 'Netherlands',
       'Pakistan', 'South Africa', 'Bangladesh',
       'United States of America', 'Africa XI', 'Ireland', 'Bermuda',
       'Scotland', 'Hong Kong', 'Afghanistan', 'United Arab Emirates',
       'Papua New Guinea', 'Namibia', 'Oman', 'Nepal', 'Thailand',
       'Jersey'], dtype=object)

In [18]:
# active teams
teams= ['New Zealand', 'India', 'Sri Lanka', 'Australia', 'England',
       'West Indies', 'Zimbabwe', 'Canada', 'Netherlands',
       'Pakistan', 'South Africa', 'Bangladesh','United States of America',
        'Ireland', 'Scotland', 'Hong Kong', 'Afghanistan',
        'United Arab Emirates', 'Namibia', 'Oman', 'Nepal', 'Thailand']

In [19]:
match_df= match_df[match_df['team1'].isin(teams)]
match_df= match_df[match_df['team2'].isin(teams)]

In [20]:
match_df.shape

(2615, 29)

In [21]:
match_df['method'].unique()

array([nan, 'D/L'], dtype=object)

In [22]:
#only matches with no rain
match_df['method']= match_df['method'].fillna(0)
match_df= match_df[match_df['method']== 0]

In [23]:
match_df= match_df[['id','gender', 'city', 'winner', 'total_runs']]

In [24]:
match_df

           id  gender          city       winner  total_runs
0       64814    male        Napier  New Zealand         255
1       64815    male  Christchurch  New Zealand         109
2       64816    male    Queenstown  New Zealand         123
3       64817    male    Wellington        India         169
4       65634    male        Sydney    Sri Lanka         344
...       ...     ...           ...          ...         ...
2726  1378198  female        Dublin    Australia         322
2727  1381214    male    Bridgetown        India         115
2728  1378199  female        Dublin    Australia         218
2729  1381215    male    Bridgetown  West Indies         182
2730  1381216    male       Tarouba        India         352

[2397 rows x 5 columns]

In [25]:
odi_df= match_df.merge(odi_ball, on= 'id')

In [26]:
odi_df= odi_df[odi_df['innings']== 2]

In [27]:
odi_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 592342 entries, 309 to 1289373
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 592342 non-null  int64
 1   gender             592342 non-null  object
 2   city               517042 non-null  object
 3   winner             583534 non-null  object
 4   total_runs_x       592342 non-null  int64
 5   season             592342 non-null  object
 6   venue              592342 non-null  object
 7   batting_team       592342 non-null  object
 8   bowling_team       592342 non-null  object
 9   innings            592342 non-null  int64
 10  over               592342 non-null  int64
 11  ball               592342 non-null  int64
 12  is_super_over      592342 non-null  int64
 13  batter             592342 non-null  object
 14  non_striker        592342 non-null  object
 15  bowler             592342 non-null  object
 16  runs_off_bat       592342 non-null  int64
 17  runs_from_extras   592342 non-null  int64
 18  total_runs_y       592342 non-null  int64
 19  is_wkt_delivery    592342 non-null  int64
 20  player_out         15718 non-null   object
 21  wkt_type           15718 non-null   object
 22  fielders_involved  9971 non-null    object
 23  byes               592342 non-null  int64
 24  legbyes            592342 non-null  int64
 25  wides              592342 non-null  int64
 26  noballs            592342 non-null  int64
 27  penalty            592342 non-null  int64
dtypes: int64(15), object(13)
memory usage: 131.1+ MB

In [28]:
odi_df['current_score']= odi_df.groupby('id')['total_runs_y'].cumsum()

In [29]:
odi_df['runs_left']= odi_df['total_runs_x'] - odi_df['current_score']

In [30]:
odi_df= odi_df[~odi_df['ball'].isin([7,8,9,10,11,12])]

In [31]:
odi_df['balls_left']= 300 - (odi_df['over']*6  + odi_df['ball'])

In [32]:
odi_df['is_wkt_delivery'].unique()

array([0, 1], dtype=int64)

In [33]:
wickets = odi_df.groupby('id')['is_wkt_delivery'].cumsum()
odi_df['wickets_left'] = 10 - wickets
odi_df.head()

,id,gender,city,winner,total_runs_x,season,venue,batting_team,bowling_team,innings,...,fielders_involved,byes,legbyes,wides,noballs,penalty,current_score,runs_left,balls_left,wickets_left
309,64814,male,Napier,New Zealand,255,2002/03,"McLean Park, Napier",India,New Zealand,2,...,NaN,0,0,0,0,0,0,255,299,10
310,64814,male,Napier,New Zealand,255,2002/03,"McLean Park, Napier",India,New Zealand,2,...,NaN,0,0,0,0,0,0,255,298,10
311,64814,male,Napier,New Zealand,255,2002/03,"McLean Park, Napier",India,New Zealand,2,...,NaN,0,0,0,0,0,0,255,297,9
312,64814,male,Napier,New Zealand,255,2002/03,"McLean Park, Napier",India,New Zealand,2,...,NaN,0,0,0,0,0,0,255,296,9
313,64814,male,Napier,New Zealand,255,2002/03,"McLean Park, Napier",India,New Zealand,2,...,NaN,0,0,0,0,0,0,255,295,9

In [34]:
# CRR & RRR
odi_df['crr']= (odi_df['current_score']*6)/ (300- odi_df['balls_left'])
odi_df['rrr']= (odi_df['runs_left']*6)/ odi_df['balls_left']

In [35]:
odi_df.shape

(576502, 34)

In [36]:
def res(row):
    return 1 if row['batting_team']== row['winner'] else 0

In [37]:
odi_df['result']= odi_df.apply(res, axis= 1)

In [38]:
df= odi_df[['gender', 'batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left', 'wickets_left', 'total_runs_x', 'crr', 'rrr', 'result']]

In [39]:
df.sample()

,gender,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,result
713096,male,India,South Africa,Kanpur,226,220,9,304,5.85,6.163636,0

In [40]:
df= df.sample(df.shape[0])

In [41]:
df.head()

,gender,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,result
306197,male,Australia,New Zealand,NaN,132,134,7,245,4.084337,5.910448,1
41335,male,Bangladesh,Pakistan,Karachi,231,187,10,303,3.823009,7.411765,0
136172,male,India,Pakistan,Karachi,190,166,9,287,4.343284,6.867470,1
544142,male,New Zealand,England,London,202,269,8,228,5.032258,4.505576,1
284618,male,India,Sri Lanka,NaN,70,191,7,143,4.018349,2.198953,1

In [42]:
df.isna().sum()

gender              0
batting_team        0
bowling_team        0
city            73397
runs_left           0
balls_left          0
wickets_left        0
total_runs_x        0
crr                 0
rrr                10
result              0
dtype: int64

In [43]:
df.dropna(inplace=True)

In [44]:
df= df[df['balls_left'] != 0]

In [45]:
df['result'].value_counts()

result
0    259107
1    243774
Name: count, dtype: int64

# ODI MEN

In [46]:
men_df= df[df['gender']== 'male']

In [47]:
men_df.head()

,gender,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,result
41335,male,Bangladesh,Pakistan,Karachi,231,187,10,303,3.823009,7.411765,0
136172,male,India,Pakistan,Karachi,190,166,9,287,4.343284,6.867470,1
544142,male,New Zealand,England,London,202,269,8,228,5.032258,4.505576,1
1192077,male,United Arab Emirates,Scotland,Aberdeen,86,62,1,263,4.462185,8.322581,0
1162511,male,United States of America,United Arab Emirates,Pearland,185,271,10,204,3.931034,4.095941,1

In [48]:
men_df= men_df[['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left', 'wickets_left', 'total_runs_x', 'crr', 'rrr', 'result']]

In [49]:
men_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,result
41335,Bangladesh,Pakistan,Karachi,231,187,10,303,3.823009,7.411765,0
136172,India,Pakistan,Karachi,190,166,9,287,4.343284,6.867470,1
544142,New Zealand,England,London,202,269,8,228,5.032258,4.505576,1
1192077,United Arab Emirates,Scotland,Aberdeen,86,62,1,263,4.462185,8.322581,0
1162511,United States of America,United Arab Emirates,Pearland,185,271,10,204,3.931034,4.095941,1
...,...,...,...,...,...,...,...,...,...,...
1216709,Namibia,United States of America,Windhoek,155,196,9,212,3.288462,4.744898,1
523037,South Africa,New Zealand,Kimberley,154,155,9,280,5.213793,5.961290,0
747810,South Africa,West Indies,Barbados,258,245,7,286,3.054545,6.318367,0
695288,India,Bangladesh,Mirpur,235,228,10,308,6.083333,6.184211,0
1264868,Oman,Ireland,Bulawayo,197,215,9,282,6.000000,5.497674,1

In [50]:
X= men_df.iloc[:,:-1]
y= men_df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=42)

In [51]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
trf= ColumnTransformer([
    ('ohe', OneHotEncoder(sparse_output= False, drop='first'), ['batting_team', 'bowling_team', 'city']),
    ('sc', StandardScaler(), ['runs_left', 'balls_left', 'wickets_left', 'total_runs_x', 'crr', 'rrr'])
], remainder= 'passthrough')

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [53]:
men_pipe= Pipeline(steps=[
    ('step1', trf),
    ('step2', LogisticRegression(solver= 'liblinear'))
])

In [54]:
men_pipe.fit(X_train, y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city']),
                                                 ('sc', StandardScaler(),
                                                  ['runs_left', 'balls_left',
                                                   'wickets_left',
                                                   'total_runs_x', 'crr',
                                                   'rrr'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [55]:
y_pred= men_pipe.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score, r2_score
print(accuracy_score(y_test, y_pred))
print(r2_score(y_test, y_pred))

0.8584413747583801
0.4331133981753488

In [57]:
men_pipe.predict(X_test)[0]

1

In [58]:
men_pipe.predict_proba(X_test)[0]

array([0.01152665, 0.98847335])

In [83]:
men_df.batting_team.unique()

array(['Bangladesh', 'India', 'New Zealand', 'United Arab Emirates',
       'United States of America', 'Australia', 'England', 'South Africa',
       'Nepal', 'West Indies', 'Pakistan', 'Sri Lanka', 'Ireland',
       'Netherlands', 'Zimbabwe', 'Afghanistan', 'Scotland', 'Oman',
       'Namibia', 'Hong Kong', 'Canada'], dtype=object)

In [84]:
men_df.city.unique()

array(['Karachi', 'London', 'Aberdeen', 'Pearland', 'Delhi', 'Durban',
       'Townsville', 'Leeds', 'Al Amarat', 'Gwalior', 'Bloemfontein',
       'Rawalpindi', 'Bulawayo', 'Kirtipur', 'Johannesburg', 'Rajkot',
       'St Vincent', 'Southampton', 'Hyderabad', 'Napier', 'Nagpur',
       'Abu Dhabi', 'Birmingham', 'Belfast', 'St Lucia', 'Colombo',
       'Fatullah', 'Rotterdam', 'Hamilton', 'Cuttack', 'Chittagong',
       'Wellington', 'Brisbane', 'Manchester', 'Mirpur', 'Guwahati',
       'Nairobi', 'Hobart', 'Ranchi', 'Harare', 'Ahmedabad', 'Canterbury',
       'East London', 'Nelson', 'Amstelveen', 'Edinburgh', 'Peshawar',
       'Mount Maunganui', 'Kanpur', 'Antigua', 'Dhaka', 'Lucknow',
       'Dublin', 'Bridgetown', 'Doha', 'Greater Noida', 'Sharjah',
       'Dubai', 'Guyana', 'Cape Town', 'Centurion', 'Vadodara',
       'Dehra Dun', 'Hambantota', 'Kolkata', 'Sydney', 'Margao',
       'St Kitts', 'Perth', 'Chandigarh', 'Port Elizabeth', 'Dunedin',
       'Grenada', 'Pune', 'Ayr', 'Chennai', 'Dambulla', 'Canberra',
       'Jamaica', 'Nottingham', 'Trinidad', 'Mumbai', 'Cardiff', 'Sylhet',
       'Kingstown', 'Paarl', 'Kuala Lumpur', 'Jamshedpur', 'Indore',
       'Kimberley', 'Lahore', 'Pietermaritzburg', 'Adelaide',
       'Chelmsford', 'Queenstown', 'Benoni', 'Jaipur', 'Multan',
       'Chattogram', 'Melbourne', 'Windhoek', 'Kochi', 'Khulna', 'Sind',
       'Faisalabad', 'Barbados', 'Christchurch', 'Chester-le-Street',
       'Port of Spain', 'Bogra', 'Visakhapatnam', 'Potchefstroom',
       'Taunton', 'Bangalore', 'Dominica', 'Bengaluru', 'Kandy',
       'Whangarei', 'North Sound', 'Bready', 'Auckland', 'Kingston',
       "St George's", 'Cairns', 'Port Moresby', 'Bristol', 'Lauderhill',
       'Darwin', 'Gqeberha', 'Providence', 'Glasgow', 'Deventer',
       'Dharamsala', 'Dharmasala', 'Faridabad', 'Gros Islet', 'Utrecht',
       'Tarouba', 'Raipur', 'Thiruvananthapuram', 'King City'],
      dtype=object)

In [61]:
import pickle
pickle.dump(men_pipe, open('men_odi_pipe.pkl', 'wb'))

# Women ODI

In [71]:
women_df= df[df['gender']== 'female']

In [72]:
women_df= women_df[['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left', 'wickets_left', 'total_runs_x', 'crr', 'rrr', 'result']]

In [73]:
women_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,result
1209344,Ireland,Pakistan,Lahore,233,148,7,336,4.065789,9.445946,0
1155725,South Africa,England,Christchurch,235,212,7,294,4.022727,6.650943,0
1101009,West Indies,South Africa,North Sound,38,2,2,186,2.979866,114.000000,0
806707,New Zealand,Australia,Auckland,200,203,9,276,4.701031,5.911330,1
1205758,England,India,Canterbury,149,100,2,334,5.550000,8.940000,0
...,...,...,...,...,...,...,...,...,...,...
778317,Sri Lanka,England,Colombo,185,164,4,241,2.470588,6.768293,0
738700,South Africa,West Indies,East London,176,208,9,233,3.717391,5.076923,0
849432,South Africa,Sri Lanka,Taunton,22,186,8,102,4.210526,0.709677,1
500919,England,India,Taunton,21,21,1,130,2.344086,6.000000,0
852250,New Zealand,India,Derby,216,203,7,266,3.092784,6.384236,0

In [69]:
df['gender'].value_counts()

gender
male      424219
female     78662
Name: count, dtype: int64

In [66]:
men_df.shape

(424219, 10)

In [74]:
women_df.shape

(78662, 10)

In [75]:
A= women_df.iloc[:,:-1]
b= women_df.iloc[:,-1]

from sklearn.model_selection import train_test_split
A_train, A_test, b_train, b_test= train_test_split(A, b, test_size= 0.25, random_state=42)

In [76]:
women_pipe= Pipeline(steps=[
    ('step1', trf),
    ('step2', LogisticRegression(solver= 'liblinear'))
])

In [77]:
women_pipe.fit(A_train, b_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city']),
                                                 ('sc', StandardScaler(),
                                                  ['runs_left', 'balls_left',
                                                   'wickets_left',
                                                   'total_runs_x', 'crr',
                                                   'rrr'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [78]:
b_pred= women_pipe.predict(A_test)

In [79]:
print(accuracy_score(b_test, b_pred))
print(r2_score(b_test, b_pred))

0.9397945693074341
0.7589627973815259

In [80]:
women_pipe.predict(A_test)[0]

1

In [81]:
women_pipe.predict_proba(A_test)[0]

array([0.01959584, 0.98040416])

In [82]:
pickle.dump(women_pipe, open('women_odi_pipe.pkl', 'wb'))

In [85]:
women_df.batting_team.unique()

array(['Ireland', 'South Africa', 'West Indies', 'New Zealand', 'England',
       'India', 'Pakistan', 'Sri Lanka', 'Netherlands', 'Zimbabwe',
       'Bangladesh', 'Australia', 'Thailand'], dtype=object)

In [86]:
women_df.city.unique()

array(['Lahore', 'Christchurch', 'North Sound', 'Auckland', 'Canterbury',
       'Lincoln', 'Taunton', 'Mumbai', 'Hambantota', 'Derby', 'Coolidge',
       'Hamilton', 'Colombo', 'Coffs Harbour', 'Chiang Mai', 'Harare',
       'Queenstown', 'Leicester', 'Vadodara', "Cox's Bazar", 'Bangalore',
       'Hobart', 'Lucknow', 'Potchefstroom', 'Kuala Lumpur', 'Karachi',
       'East London', 'Mount Maunganui', 'Pretoria', 'Bloemfontein',
       'Bristol', 'London', 'Wellington', 'Paarl', 'Melbourne',
       'Brisbane', 'Worcester', 'Hove', 'Dublin', 'Kandy', 'Dunedin',
       'Durban', 'Southampton', 'Sydney', 'Johannesburg', 'Kimberley',
       'Bowral', 'Mackay', 'Leeds', 'Bangkok', 'FTZ Sports Complex',
       'Kurunegala', 'Nagpur', 'Benoni', 'Chelmsford', 'Brighton',
       'Gros Islet', 'Centurion', 'Adelaide', 'Perth', 'Nelson',
       'Northampton', 'Canberra', 'Katunayake', 'Dubai', 'Chennai',
       'Barbados', 'The Hague', 'Dhaka', 'Napier', 'Scarborough',
       'Amstelveen', 'Galle', 'Loughborough', 'Bulawayo'], dtype=object)