In [1]:
import pandas as pd
import numpy as np

In [2]:
match= pd.read_csv('matches.csv')
deli= pd.read_csv('deliveries.csv')

In [3]:
match.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [4]:
match.shape

(1095, 20)

In [5]:
deli.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [6]:
deli.shape

(260920, 17)

In [7]:
total_score_df= deli.groupby(['match_id', 'inning']).sum()['total_runs'].reset_index()

In [8]:
total_score_df= total_score_df[total_score_df['inning']== 1]

In [9]:
total_score_df['total_runs']= total_score_df['total_runs'] + 1

In [10]:
total_score_df

      match_id  inning  total_runs
0       335982       1         223
2       335983       1         241
4       335984       1         130
6       335985       1         166
8       335986       1         111
...        ...     ...         ...
2207   1426307       1         215
2209   1426309       1         160
2211   1426310       1         173
2213   1426311       1         176
2215   1426312       1         114

[1095 rows x 3 columns]

# merge total_score_df to match.csv on 'id'

In [11]:
match_df= match.merge(total_score_df[['match_id', 'total_runs']], left_on= 'id', right_on= 'match_id')

In [12]:
match_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,total_runs
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,335982,223
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,335983,241
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,335984,130
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,335985,166
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,335986,111

# removing old teams

In [13]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [14]:
teams= [
    'Mumbai Indians', 
    'Kolkata Knight Riders',
    'Rajasthan Royals',
    'Chennai Super Kings',
    'Sunrisers Hyderabad',
    'Delhi Capitals',
    'Punjab Kings',
    'Lucknow Super Giants', 
    'Gujarat Titans',
    'Royal Challengers Bengaluru'
]

In [15]:
match_df['team1']= match_df['team1'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['team2']= match_df['team2'].str.replace('Delhi Daredevils', 'Delhi Capitals')
match_df['winner']= match_df['winner'].str.replace('Delhi Daredevils', 'Delhi Capitals')

match_df['team1']= match_df['team1'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
match_df['team2']= match_df['team2'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
match_df['winner']= match_df['winner'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')

match_df['team1']= match_df['team1'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['team2']= match_df['team2'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
match_df['winner']= match_df['winner'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

match_df['team1']= match_df['team1'].str.replace('Kings XI Punjab', 'Punjab Kings')
match_df['team2']= match_df['team2'].str.replace('Kings XI Punjab', 'Punjab Kings')
match_df['winner']= match_df['winner'].str.replace('Kings XI Punjab', 'Punjab Kings')

In [16]:
match_df= match_df[match_df['team1'].isin(teams)]
match_df= match_df[match_df['team2'].isin(teams)]

In [17]:
match_df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,total_runs
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,335982,223
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,335983,241
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,335984,130
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,335985,166
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Sunrisers Hyderabad,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,335986,111

In [18]:
match_df.shape

(980, 22)

# taking only matches with no rain

In [19]:
match_df['method']= match_df['method'].fillna(0)

In [20]:
match_df= match_df[match_df['method']== 0]

In [21]:
match_df= match_df[['match_id', 'city', 'winner', 'total_runs']]

In [22]:
match_df.head()

   match_id        city                       winner  total_runs
0    335982   Bangalore        Kolkata Knight Riders         223
1    335983  Chandigarh          Chennai Super Kings         241
2    335984       Delhi               Delhi Capitals         130
3    335985      Mumbai  Royal Challengers Bengaluru         166
4    335986     Kolkata        Kolkata Knight Riders         111

In [23]:
delivery_df= match_df.merge(deli, on= 'match_id')

In [24]:
delivery_df= delivery_df[delivery_df['inning']== 2]

In [25]:
delivery_df['current_score']= delivery_df.groupby('match_id')['total_runs_y'].cumsum()

In [26]:
delivery_df['runs_left']= delivery_df['total_runs_x']-delivery_df['current_score']

In [27]:
delivery_df['balls_left']= 120 - (delivery_df['over']*6  + delivery_df['ball'])

In [28]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
124,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,1,NaN,0,NaN,NaN,NaN,1,222,119
125,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1,1,wides,0,NaN,NaN,NaN,2,221,118
126,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,0,NaN,0,NaN,NaN,NaN,2,221,117
127,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0,1,NaN,0,NaN,NaN,NaN,3,220,116
128,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0,1,NaN,0,NaN,NaN,NaN,4,219,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,0,1,NaN,0,NaN,NaN,NaN,110,4,61
230978,1426312,Chennai,Kolkata Knight Riders,114,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,111,3,60
230979,1426312,Chennai,Kolkata Knight Riders,114,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,112,2,59
230980,1426312,Chennai,Kolkata Knight Riders,114,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,0,1,NaN,0,NaN,NaN,NaN,113,1,58
230981,1426312,Chennai,Kolkata Knight Riders,114,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,114,0,57

In [29]:
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")

In [30]:
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x if x == "0" else "1")

In [31]:
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')

In [32]:
wickets = delivery_df.groupby('match_id')['player_dismissed'].cumsum()
delivery_df['wickets'] = 10 - wickets
delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets
124,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,1,NaN,0,0,NaN,NaN,1,222,119,10
125,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1,wides,0,0,NaN,NaN,2,221,118,10
126,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,NaN,0,0,NaN,NaN,2,221,117,10
127,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,1,NaN,0,0,NaN,NaN,3,220,116,10
128,335982,Bangalore,Kolkata Knight Riders,223,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,1,NaN,0,0,NaN,NaN,4,219,115,10

In [33]:
# CRR & RRR
delivery_df['crr']= (delivery_df['current_score']*6)/ (120- delivery_df['balls_left'])
delivery_df['rrr']= (delivery_df['runs_left']*6)/ delivery_df['balls_left']

In [34]:
delivery_df['batting_team']= delivery_df['batting_team'].str.replace('Delhi Daredevils', 'Delhi Capitals')
delivery_df['bowling_team']= delivery_df['bowling_team'].str.replace('Delhi Daredevils', 'Delhi Capitals')

delivery_df['batting_team']= delivery_df['batting_team'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
delivery_df['bowling_team']= delivery_df['bowling_team'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')

delivery_df['batting_team']= delivery_df['batting_team'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
delivery_df['bowling_team']= delivery_df['bowling_team'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

delivery_df['batting_team']= delivery_df['batting_team'].str.replace('Kings XI Punjab', 'Punjab Kings')
delivery_df['bowling_team']= delivery_df['bowling_team'].str.replace('Kings XI Punjab', 'Punjab Kings')

delivery_df['city']= delivery_df['city'].str.replace('Bangalore', 'Bengaluru')

In [35]:
delivery_df= delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df= delivery_df[delivery_df['bowling_team'].isin(teams)]

In [36]:
delivery_df.sample()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets,crr,rrr
125265,1136577,Pune,Chennai Super Kings,205,2,Rajasthan Royals,Chennai Super Kings,4,1,BA Stokes,...,0,0,NaN,NaN,31,174,95,8,7.44,10.989474

In [37]:
def res(row):
    return 1 if row['batting_team']== row['winner'] else 0

In [38]:
delivery_df['result']= delivery_df.apply(res, axis= 1)

In [39]:
df= delivery_df[['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left', 'wickets', 'total_runs_x', 'crr', 'rrr', 'result']]

In [40]:
df= df.sample(df.shape[0])

In [41]:
df.dropna(inplace= True)

In [42]:
df= df[df['balls_left'] != 0]

In [43]:
df['result'].value_counts()

result
1    54429
0    50914
Name: count, dtype: int64

In [44]:
df

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr,result
95841,Rajasthan Royals,Mumbai Indians,Ahmedabad,90,56,9,165,7.031250,9.642857,1
109992,Mumbai Indians,Kolkata Knight Riders,Mumbai,160,109,9,175,8.181818,8.807339,1
89614,Kolkata Knight Riders,Sunrisers Hyderabad,Hyderabad,43,32,8,143,6.818182,8.062500,1
137093,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,162,96,10,199,9.250000,10.125000,1
70737,Chennai Super Kings,Rajasthan Royals,Chennai,107,68,9,186,9.115385,9.441176,1
...,...,...,...,...,...,...,...,...,...,...
202554,Rajasthan Royals,Lucknow Super Giants,Jaipur,51,29,7,155,6.857143,10.551724,0
217753,Delhi Capitals,Kolkata Knight Riders,Visakhapatnam,203,73,6,273,8.936170,16.684932,0
133756,Kolkata Knight Riders,Sunrisers Hyderabad,Hyderabad,17,16,7,173,9.000000,6.375000,1
120426,Kolkata Knight Riders,Punjab Kings,Chandigarh,129,97,9,168,10.173913,7.979381,0
227913,Punjab Kings,Royal Challengers Bengaluru,Dharamsala,61,18,1,242,10.647059,20.333333,0

# Model Training

In [45]:
X= df.iloc[:,:-1]
y= df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.30, random_state=0)

In [46]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
trf= ColumnTransformer([
    ('ohe', OneHotEncoder(sparse_output= False, drop='first'), ['batting_team', 'bowling_team', 'city']),
    #('sc', StandardScaler(), ['runs_left', 'balls_left', 'wickets', 'total_runs_x', 'crr', 'rrr'])
], remainder= 'passthrough')

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [48]:
pipe= Pipeline(steps=[
    ('step1', trf),
    ('step2', LogisticRegression(solver= 'liblinear'))
])

In [49]:
pipe.fit(X_train, y_train)

C:\Users\Asus\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [50]:
y_pred= pipe.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8011264753346201

In [52]:
pipe.predict(X_test)[0]

1

In [53]:
pipe.predict_proba(X_test)[0]

array([0.24298441, 0.75701559])

In [54]:
X_test.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr
218460,Rajasthan Royals,Royal Challengers Bengaluru,Jaipur,123,78,9,184,8.714286,9.461538
89844,Rajasthan Royals,Mumbai Indians,Ahmedabad,104,48,3,179,6.250000,13.000000
15530,Delhi Capitals,Royal Challengers Bengaluru,Port Elizabeth,70,45,8,150,6.400000,9.333333
180669,Mumbai Indians,Rajasthan Royals,Mumbai,81,47,8,194,9.287671,10.340426
20643,Punjab Kings,Sunrisers Hyderabad,Kimberley,42,22,4,169,7.775510,11.454545

In [55]:
df.city.unique()

array(['Ahmedabad', 'Mumbai', 'Hyderabad', 'Chennai', 'Dharamsala',
       'Bengaluru', 'Pune', 'Abu Dhabi', 'Kolkata', 'Port Elizabeth',
       'Mohali', 'Delhi', 'Ranchi', 'Dubai', 'Bloemfontein', 'Sharjah',
       'Jaipur', 'Chandigarh', 'Lucknow', 'Durban', 'Indore', 'Centurion',
       'Navi Mumbai', 'East London', 'Nagpur', 'Johannesburg', 'Cuttack',
       'Visakhapatnam', 'Cape Town', 'Guwahati', 'Raipur', 'Kimberley'],
      dtype=object)

In [56]:
import pickle
pickle.dump(pipe, open('ipl_pipe.pkl', 'wb'))

# Toss

In [57]:
match.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [58]:
toss_df= match[['team1', 'team2', 'city', 'match_type', 'toss_winner']]

In [59]:
def res(row):
    return 1 if row['team1']== row['toss_winner'] else 0

In [60]:
toss_df['result']= toss_df.apply(res, axis= 1)

C:\Users\Asus\AppData\Local\Temp\ipykernel_7756\549844934.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  toss_df['result']= toss_df.apply(res, axis= 1)

In [61]:
toss_df= toss_df[['team1', 'team2', 'city', 'match_type', 'result']]

In [62]:
toss_df.head()

,team1,team2,city,match_type,result
0,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,League,1
1,Kings XI Punjab,Chennai Super Kings,Chandigarh,League,0
2,Delhi Daredevils,Rajasthan Royals,Delhi,League,0
3,Mumbai Indians,Royal Challengers Bangalore,Mumbai,League,1
4,Kolkata Knight Riders,Deccan Chargers,Kolkata,League,0

In [63]:
toss_df['team1']= toss_df['team1'].str.replace('Delhi Daredevils', 'Delhi Capitals')
toss_df['team2']= toss_df['team2'].str.replace('Delhi Daredevils', 'Delhi Capitals')
#toss_df['toss_winner']= toss_df['toss_winner'].str.replace('Delhi Daredevils', 'Delhi Capitals')

toss_df['team1']= toss_df['team1'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
toss_df['team2']= toss_df['team2'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
#toss_df['toss_winner']= toss_df['toss_winner'].str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')

toss_df['team1']= toss_df['team1'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
toss_df['team2']= toss_df['team2'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')
#toss_df['toss_winner']= toss_df['toss_winner'].str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

toss_df['team1']= toss_df['team1'].str.replace('Kings XI Punjab', 'Punjab Kings')
toss_df['team2']= toss_df['team2'].str.replace('Kings XI Punjab', 'Punjab Kings')
#toss_df['toss_winner']= toss_df['toss_winner'].str.replace('Kings XI Punjab', 'Punjab Kings')

toss_df['city']= toss_df['city'].str.replace('Bangalore', 'Bengaluru')

In [64]:
toss_df= toss_df[toss_df['team1'].isin(teams)]
toss_df= toss_df[toss_df['team2'].isin(teams)]

In [65]:
toss_df= toss_df[~toss_df['match_type'].isin(['Elimination Final', '3rd Place Play-Off', 'Semi Final'])]

In [66]:
toss_df.shape

(970, 5)

In [67]:
toss_df.head()

,team1,team2,city,match_type,result
0,Royal Challengers Bengaluru,Kolkata Knight Riders,Bengaluru,League,1
1,Punjab Kings,Chennai Super Kings,Chandigarh,League,0
2,Delhi Capitals,Rajasthan Royals,Delhi,League,0
3,Mumbai Indians,Royal Challengers Bengaluru,Mumbai,League,1
4,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,League,0

In [68]:
Xt= toss_df.iloc[:,:-1]
yt= toss_df.iloc[:,-1]

from sklearn.model_selection import train_test_split
Xt_train, Xt_test, yt_train, yt_test= train_test_split(Xt, yt, test_size= 0.20, random_state=42)

In [69]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
trft= ColumnTransformer([
    ('ohe', OneHotEncoder(sparse_output= False, drop='first'), ['team1', 'team2', 'city', 'match_type'])
], remainder= 'passthrough')

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [71]:
pipe_t= Pipeline(steps=[
    ('step1', trft),
    ('step2', RandomForestClassifier(random_state=42))
])

In [72]:
pipe_t.fit(Xt_train, yt_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['team1', 'team2', 'city',
                                                   'match_type'])])),
                ('step2', RandomForestClassifier(random_state=42))])

In [73]:
yt_pred= pipe_t.predict(Xt_test)

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(yt_test, yt_pred)

0.5927835051546392

In [75]:
print(match['toss_winner'].value_counts(normalize=True))

toss_winner
Mumbai Indians                 0.130594
Kolkata Knight Riders          0.111416
Chennai Super Kings            0.111416
Rajasthan Royals               0.109589
Royal Challengers Bangalore    0.103196
Sunrisers Hyderabad            0.080365
Kings XI Punjab                0.077626
Delhi Daredevils               0.073059
Delhi Capitals                 0.045662
Deccan Chargers                0.039269
Punjab Kings                   0.021918
Gujarat Titans                 0.020091
Pune Warriors                  0.018265
Lucknow Super Giants           0.017352
Gujarat Lions                  0.013699
Kochi Tuskers Kerala           0.007306
Royal Challengers Bengaluru    0.007306
Rising Pune Supergiants        0.006393
Rising Pune Supergiant         0.005479
Name: proportion, dtype: float64

In [76]:
pipe_t.predict_proba(Xt_test)[0]

array([0.58145455, 0.41854545])

In [77]:
import pickle
pickle.dump(pipe_t, open('ipl_toss_pipe.pkl', 'wb'))

In [78]:
toss_df['match_type'].unique()

array(['League', 'Final', 'Qualifier 1', 'Qualifier 2', 'Eliminator'],
      dtype=object)